version: '3.7'

services:
  server:
    image: bertytech/berty:latest
    restart: on-failure
    environment:
      - RDVP_PK # loaded from .env
    entrypoint: rdvp
    ports:
      - 4040:4040
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command:
      - --debug
      - serve
      - "--db=:memory:"
      - "--pk=$RDVP_PK"
      - "-l"
      - "/ip4/0.0.0.0/tcp/4040"
